### ISSUE TITLE
windows Path is not merged with MSYS2 PATH

### ISSUE THREAD

**Issue by pksn** [msys2/msys2.github.io#20]
###  Windows PATH is not merged with MSYS2 PATH 
On a fresh install, my windows PATH was merged and I was able to invoke emacs (windows installation) from MSYS. Later after pacman -Syuu and installing nano and some other packages which I need. My Windows PATH is not merged anymore. 

I tried to look into some WiKi pages, if I should do more steps to configure but I coudn't find more info.

#### MSYS PATH: 
My complete MYSYS PATH
in .bashrc I exported go/bin manually. I don't want to manually import all windows programs. if that is the solution I wouldn't go for Msys.  May be I messed up the installation. 

`declare -x PATH="/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/d/soft/go/bin`

#### Windows PATH:
is huge for example I have the following additional programs which I would like to invoke from Msys. Is that possible? 

A snapshot of echo $PATH from ming64 (Git Bash) which reads my windows PATH perfectly. 
`
/c/Program Files/Java/jre1.8.0_73/bin;/d/soft/OpenVPN/bin:/d/soft/emacs-24.5-bin-i686-mingw32/bin:/c/Program Files/Java/jdk1.8.0_73/bin:/d/soft/emacs-24.5-bin-i686-mingw32/pka/hunspell-1.3.2/bin
`

What have I done ? Some wrong configuration?

**Comment by mingwandroid** [comment]
Most of that software we provide (hunspell, Emacs) so you should use our versions since you get the benefits of pacman updates,  shared libraries and a single point of maintainance.

Also we can do without the big reports from software we don't control do we took the step to remove that stuff from the PATH by default.

Regardless, if you really want it back, edit msys2_shell.bat or set the following env var in windows: MSYS2_PATH_TYPE=inherit
