### ISSUE TITLE
Uninstaller traverses junctions, deleting files it shouldn't

### ISSUE THREAD

**Issue by gfody** [msys2/msys2.github.io#4]
I created an ntfs junction in my msys home directory to my windows user directory. The uninstaller followed it and started wiping out my windows user directory before I realized what was happening and killed the process. Still the damage was incredibly devastating.. truly horrific. Luckily I have a backup that is not too old but I am very sad to be doing that right now. God dammit.

**Comment by mingwandroid** [comment]
Yes, this is a terrible oversight for which I apologise.

The last time I was made aware of it [1] I tested it with mklink /D as the information given said that it happened with symbolic links. The uninstaller did not follow the symlink target and being unable to communicate with the reporter, I stopped investigating.

Since your report I've taken another look and indeed Qt doesn't consider junction points to be symbolic links [2]. Personally I think this is crazy given the devastation. Also the reasons for this seem to be vague at best. To me, it seems that they decided that an autotest failure mattered more than users' data.

I will probably revert [3] and rebuild to see if this fixes it.

[1] http://sourceforge.net/p/msys2/mailman/message/33093184/
[2] https://bugreports.qt.io/browse/QTBUG-20431
[3] https://codereview.qt-project.org/#/c/13573/
