### ISSUE TITLE
zst archive

### ISSUE THREAD

**Issue by uzhas-sovka** [msys2/msys2.github.io#49]
Can't install zst-archived packages.

`error: could not open file /var/cache/pacman/pkg/libarchive-3.4.2-3-x86_64.pkg.tar.zst: Unrecognized archive format`

**Comment by lazka** [comment]
try `pacman -Sy pacman` first

**Comment by uzhas-sovka** [comment]
```
# pacman -Sy pacman
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
```
and so on, no errors.

But then
```
# stack exec -- pacman -Sy mingw64/mingw-w64-x86_64-icu

error: could not open file /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-libs-10.1.0-2-any.pkg.tar.zst: Unrecognized archive format
```
Now I download and unpack zst file manually and install it via
`pacman -U <packagefile.tar.xz>`

**Comment by wutipong** [comment]
Not really sure if this will help or hurt :).

I've got the same error as I install MSYS2 and tried to to update the system. What I do next is to upgrade the `pacman` to 5.2.1-6 by download the file manual from a mirror, and then install it using `pacman -U`. Then at this point `pacman` should be able to install .zst package.

However after I update the MSYS2, it does not run any more for some reason.... Probably because it upgrade the msys2-runtime and cause some kind of problem ...

Anyway I'd love to have the msys2 installer that comes with pacman 5.2. That should solve the problem when freshly installation trying to upgrade msys2.

**Comment by uzhas-sovka** [comment]
I stepped back to
`pacman -U <packagefile.tar.xz>`
from local unzipped file.

**Comment by lazka** [comment]
This should be fixed now. Can anyone confirm?

**Comment by wutipong** [comment]
@lazka I can't really confirm because as soon as I update to the new msys2-runtime (if I recall correctly), msys2 now does not run anymore.

I think it's a separated issue so I will open a new issue, if you don't mind.

**Comment by lazka** [comment]
That's a separate issue, but should be solved by either rebooting or loggin in and out of your user account.

**Comment by lazka** [comment]
We've added some improvements that should hopefully prevent both of those issues with similar future updates.

There is also a new installer out including those newer packages from the start.

**Comment by gMan1990** [comment]
> try `pacman -Sy pacman` first

@lazka
```text
x@DESKTOP-x ~> man pacman|tail -n 1
Pacman 5.2.1                                                                                                                   2020-06-06                                                                                                                      PACMAN(8)
x@DESKTOP-x ~> pacman -V
x@DESKTOP-x ~> pacman --version
x@DESKTOP-x ~> pacman --help
x@DESKTOP-x ~>
```

Nothing output and can't install packages. Please help me!

**Comment by lazka** [comment]
@gMan1990 `taskkill /f /fi "MODULES eq msys-2.0.dll"`
