### ISSUE TITLE
Please mirror installer binaries elsewhere

### ISSUE THREAD

**Issue by achadwick** [msys2/msys2.github.io#6]
Please could the installer binaries be mirrored elsewhere, perhaps on github, perhaps as release binaries of this project?

* Allow access when SourceForge is down (my [current](http://www.theregister.co.uk/2015/07/17/souceforge_titsup/) itch, but it seems an increasingly frequent occurrence of late) [**EDIT** slightly more reputable and newsy link]
* Avoids irritations like Google and uBlock<sub>O</sub> flagging SourceForge as a source of malware (gorhill/uBlock#373)

On the wider picture, msys2 needs to be not using SourceForge at all. From uBlock's rationale for blocking the entire domain by default:

* 2015-06-18: http://www.information-age.com/industry/software/123459675/hotbed-malware-another-blow-sourceforge-google-discovers-588-pages-malicious-software
* 2015-06-02: https://blog.l0cal.com/2015/06/02/what-happened-to-sourceforge/
* 2015-05-28: http://libregraphicsworld.org/blog/entry/anatomy-of-sourceforge-gimp-controversy
* 2015-05-17: http://lifehacker.com/antiadware-gets-rid-of-bundled-crapware-on-popular-down-1702818594
* 2015-03-11: http://blog.emsisoft.com/2015/03/11/mind-the-pup-top-download-portals-to-avoid/
* 2015-01-21: http://www.howtogeek.com/207692/yes-every-freeware-download-site-is-serving-crapware-heres-the-proof/
* 2014-11-25: http://blog.tedd.no/2014/11/25/sourceforge-malware/

though I'm sure that you're aware of that, and that it's not going to happen overnight.

**Comment by staticfloat** [comment]
+1 from me; it kind of defeats the purpose of having this GitHub-based installation site if it redirects to suorceforge.

**Comment by achadwick** [comment]
<https://www.mirrorservice.org/sites/downloads.sourceforge.net/m/ms/msys2/> is one stopgap, for now. If you just want the installer.

**Comment by tkelman** [comment]
There have been longer discussions on this on the (ironically sourceforge-hosted) mailing lists, but this really needs to happen. Nobody really cares that much if mailing lists are separate from version control are separate from binary hosting. Use the best tool for the job, not sourceforge. Homebrew switched to bintray a while ago, msys2 should do the same for package binaries. Github releases should be good enough for the installer binaries since those don't need to change as often and aren't auto-updated.

**Comment by photex** [comment]
+1

**Comment by Alexpux** [comment]
Mirrored here: http://repo.msys2.org/distrib/
